package export

import (
	"fmt"
	"sort"
	"strings"

	"github.com/inframap/inframap/internal/graph"
)

// FormatTerraform reverse-engineers the live graph into a starter main.tf.
const FormatTerraform Format = "terraform"

// tfType maps graph node types to Terraform resource types.
var tfType = map[string]string{
	"vpc":              "aws_vpc",
	"subnet":           "aws_subnet",
	"internet_gateway": "aws_internet_gateway",
	"nat_gateway":      "aws_nat_gateway",
	"security_group":   "aws_security_group",
	"alb":              "aws_lb",
	"ec2":              "aws_instance",
	"rds":              "aws_db_instance",
	"elasticache":      "aws_elasticache_cluster",
	"s3_bucket":        "aws_s3_bucket",
	"cloudfront":       "aws_cloudfront_distribution",
	"route53":          "aws_route53_zone",
	"dns_record":       "aws_route53_record",
	"ecs_cluster":      "aws_ecs_cluster",
	"ecs_service":      "aws_ecs_service",
	"lambda":           "aws_lambda_function",
	"iam_role":         "aws_iam_role",
	"sns":              "aws_sns_topic",
	"sqs":              "aws_sqs_queue",
	"cloudwatch":       "aws_cloudwatch_metric_alarm",
	"volume":           "aws_ebs_volume",
	// azure
	"resource_group":  "azurerm_resource_group",
	"vm":              "azurerm_linux_virtual_machine",
	"vnet":            "azurerm_virtual_network",
	"nsg":             "azurerm_network_security_group",
	"storage_account": "azurerm_storage_account",
	"sql_server":      "azurerm_mssql_server",
	"app_service":     "azurerm_linux_web_app",
	"aks":             "azurerm_kubernetes_cluster",
	// gcp
	"gce_instance": "google_compute_instance",
	"gcp_network":  "google_compute_network",
	"subnetwork":   "google_compute_subnetwork",
	"gcs_bucket":   "google_storage_bucket",
	"cloud_sql":    "google_sql_database_instance",
}

// attribute keys worth emitting per node type (metadata key → tf argument)
var tfArgs = map[string]map[string]string{
	"aws_vpc":                 {"cidr": "cidr_block"},
	"aws_subnet":              {"cidr": "cidr_block", "az": "availability_zone"},
	"aws_instance":            {"instance_type": "instance_type", "ami": "ami"},
	"aws_db_instance":         {"engine": "engine", "version": "engine_version", "instance_class": "instance_class"},
	"aws_elasticache_cluster": {"engine": "engine", "node_type": "node_type"},
	"aws_lambda_function":     {"runtime": "runtime", "handler": "handler"},
}

func exportTerraform(g *graph.Graph) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by InfraMap — reverse-engineered from the live graph.\n")
	b.WriteString("# Review before applying: values are best-effort, references are by name.\n\n")

	providers := map[string]bool{}
	nodes := g.NodeSlice()
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].ID < nodes[j].ID })

	var body strings.Builder
	for _, n := range nodes {
		rt, ok := tfType[n.Type]
		if !ok {
			continue // regions, docker resources, etc. — not terraform-managed
		}
		switch {
		case strings.HasPrefix(rt, "aws_"):
			providers["aws"] = true
		case strings.HasPrefix(rt, "azurerm_"):
			providers["azurerm"] = true
		case strings.HasPrefix(rt, "google_"):
			providers["google"] = true
		}

		body.WriteString(fmt.Sprintf("resource %q %q {\n", rt, tfName(n.ID)))
		if args, ok := tfArgs[rt]; ok {
			keys := make([]string, 0, len(args))
			for k := range args {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, metaKey := range keys {
				if v := n.Metadata[metaKey]; v != "" {
					body.WriteString(fmt.Sprintf("  %s = %q\n", args[metaKey], firstWord(v)))
				}
			}
		}
		body.WriteString(fmt.Sprintf("  tags = { Name = %q }\n", n.Name))
		if n.Parent != "" {
			body.WriteString(fmt.Sprintf("  # parent: %s\n", n.Parent))
		}
		body.WriteString("}\n\n")
	}

	if len(providers) > 0 {
		b.WriteString("terraform {\n  required_providers {\n")
		names := make([]string, 0, len(providers))
		for p := range providers {
			names = append(names, p)
		}
		sort.Strings(names)
		for _, p := range names {
			src := map[string]string{"aws": "hashicorp/aws", "azurerm": "hashicorp/azurerm", "google": "hashicorp/google"}[p]
			b.WriteString(fmt.Sprintf("    %s = { source = %q }\n", p, src))
		}
		b.WriteString("  }\n}\n\n")
	}
	b.WriteString(body.String())
	return b.String(), nil
}

func tfName(id string) string {
	s := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			return r
		}
		return '_'
	}, id)
	if s == "" || (s[0] >= '0' && s[0] <= '9') {
		s = "r_" + s
	}
	return s
}

func firstWord(s string) string {
	if f := strings.Fields(s); len(f) > 0 {
		return f[0]
	}
	return s
}
